import type { ProductRow } from "@/types/commerce";

/**
 * Official TYSH / Tuya Smart Product Catalogue
 * Sourced from Guangdong Mingshen Smart Information Technology Co., LTD (Tuya Smart Ecosystem)
 * Converted to PKR (Exchange rate ~280 PKR / USD)
 */
export const TUYA_PRODUCTS: ProductRow[] = [
  // ==========================================
  // SECTION 1: TUYA SMART DOOR LOCKS (Pages 4–28)
  // ==========================================
  {
    id: "tysh-ty20",
    title: "Tuya TYSH-TY20 Face Recognition Automatic Smart Lock - WiFi",
    slug: "tysh-ty20-automatic-smart-lock",
    category: "Smart Door Locks",
    price_pkr: 13000,
    stock: 45,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Obsidian Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80",
    ],
    description:
      "Fully automatic Tuya Smart Lock equipped with infrared 3D face recognition and contactless palm vein scanner. Supports Tuya WiFi App, fingerprint, passcode, RFID card, and emergency mechanical key. Aluminum alloy chassis with 4200mAh rechargeable lithium battery.",
    specs: {
      Model: "TYSH-TY20",
      "Unlock Methods":
        "Tuya App, 3D Face ID, Palm Vein, Fingerprint, Passcode, IC Card, Mechanical Key",
      Connectivity: "WiFi 2.4GHz (Direct connect, no gateway required)",
      Battery: "4200mAh Lithium Rechargeable (Type-C emergency port)",
      Material: "High-density Aluminum Alloy",
      Mortise: "Standard 6068 Anti-theft Lock Body",
      Languages: "14 System Voice Prompts",
      "Door Thickness": "40mm - 120mm",
    },
    tags: ["Tuya", "Smart Lock", "Face ID", "Palm Vein", "WiFi", "Automatic Lock"],
  },
  {
    id: "tysh-ty21",
    title: "Tuya TYSH-TY21 Video Intercom Automatic Smart Lock - WiFi",
    slug: "tysh-ty21-smart-lock-video-intercom",
    category: "Smart Door Locks",
    price_pkr: 13440,
    stock: 38,
    discount_pct: 5,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Space Gray",
    image_url:
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80",
    ],
    description:
      "Equipped with live video surveillance and indoor HD peephole screen. Real-time video intercom with Tuya app when visitors ring the doorbell. Supports 3D face ID, palm vein, fingerprint, and virtual password.",
    specs: {
      Model: "TYSH-TY21",
      "Unlock Methods":
        "Tuya App, Face Recognition, Palm Vein, Fingerprint, Passcode, IC Card, Key",
      Camera: "HD Wide-Angle Camera with Infrared Night Vision",
      Screen: "Indoor Color IPS Screen",
      Battery: "4200mAh Lithium Rechargeable",
      Mortise: "6068 Lock Body",
      Languages: "14 Languages Supported",
    },
    tags: ["Tuya", "Smart Lock", "Video Intercom", "Peephole Camera", "WiFi"],
  },
  {
    id: "tysh-ty17-ai",
    title: "Tuya TYSH-TY17-Ai Voice Controlled Smart Door Lock - WiFi",
    slug: "tysh-ty17-ai-voice-smart-lock",
    category: "Smart Door Locks",
    price_pkr: 11760,
    stock: 50,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Matte Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Voice-activated smart lock featuring offline & online AI voice recognition ('Hi Alexa' / 'Hi Lucy'). Hands-free verification combined with palm vein sensor, video surveillance, and Tuya smart home scene automation.",
    specs: {
      Model: "TYSH-TY17-Ai",
      "AI Features": "Voice Command Recognition, Alexa & Lucy Integration",
      "Unlock Methods": "Voice Prompt, Palm Vein, Face ID, Fingerprint, Password, Card, App",
      Battery: "5000mAh High-Capacity Lithium",
      Material: "Aviation-grade Aluminum",
      Mortise: "6068 Standard Mortise",
    },
    tags: ["Tuya", "Smart Lock", "Voice Control", "Alexa", "AI", "Palm Vein"],
  },
  {
    id: "tysh-la09",
    title: "Tuya TYSH-LA09 Flagship AI Smart Door Lock - WiFi",
    slug: "tysh-la09-flagship-ai-smart-lock",
    category: "Smart Door Locks",
    price_pkr: 18200,
    stock: 30,
    discount_pct: 8,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Titanium Gold / Black",
    image_url:
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80",
    description:
      "Commercial and luxury villa grade automatic smart lock. Features Hi-Lucy AI voice interaction, video surveillance stream, 24 multi-lingual voice navigation, 3D structured light facial recognition, and fast palm vein unlocking.",
    specs: {
      Model: "TYSH-LA09",
      "Unlock Methods":
        "AI Voice, Face ID, Palm Vein, Video Remote App, Biometric Fingerprint, RFID",
      Languages: "24 Languages International Support",
      Battery: "4200mAh Lithium Pack + Backup Battery",
      Mortise: "6068 / 6590 Heavy Duty Lock Body",
      Chassis: "Reinforced Zinc & Aluminum Alloy",
    },
    tags: ["Tuya", "Luxury Lock", "AI Smart Lock", "Palm Vein", "Villa Lock"],
  },
  {
    id: "tysh-ty07",
    title: "Tuya TYSH-TY07 Dual-Battery Surveillance Smart Lock - WiFi",
    slug: "tysh-ty07-dual-battery-smart-lock",
    category: "Smart Door Locks",
    price_pkr: 21280,
    stock: 25,
    discount_pct: 10,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Obsidian Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Never run out of power: comes equipped with 2 separate 4200mAh hot-swappable lithium batteries. Full HD outdoor security camera with auto PIR human detection and remote video unlocking via Tuya App.",
    specs: {
      Model: "TYSH-TY07",
      "Battery System": "Dual Independent Lithium Batteries (2x 4200mAh = 8400mAh total)",
      Camera: "1080P Ultra-Wide Security Camera with IR Night Vision",
      "Unlock Methods": "Face, Palm, Video Call, Fingerprint, Passcode, Card, Key",
      Mortise: "6068 / 6085 Stainless Steel Mortise",
    },
    tags: ["Tuya", "Dual Battery", "Video Lock", "Surveillance", "Smart Lock"],
  },
  {
    id: "tysh-ty13",
    title: "Tuya TYSH-TY13 CNC Precision Automatic Smart Lock - WiFi",
    slug: "tysh-ty13-cnc-precision-smart-lock",
    category: "Smart Door Locks",
    price_pkr: 21840,
    stock: 20,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Brushed Graphite",
    image_url:
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80",
    description:
      "Precision CNC milled from a solid billet of aviation alloy. Seamless unibody construction provides maximum physical anti-drill, anti-pry, and anti-impact security.",
    specs: {
      Model: "TYSH-TY13",
      Craftsmanship: "100% Solid Billet CNC Machining",
      Biometrics: "Sub-surface Palm Vein Scanner + 3D Face ID",
      Battery: "4200mAh Lithium Pack",
      Mortise: "6068 High Security Mortise",
    },
    tags: ["Tuya", "CNC Machined", "High Security", "Smart Lock", "Palm Vein"],
  },
  {
    id: "tysh-tys7",
    title: "Tuya TYSH-TYS7 4-Inch Touchscreen Smart Lock - WiFi",
    slug: "tysh-tys7-smart-lock-4inch-touchscreen",
    category: "Smart Door Locks",
    price_pkr: 18480,
    stock: 32,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Midnight Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Features a built-in 4-inch IPS capacitive touch screen on the interior panel for viewing live outdoor video, door status logs, and configuring lock settings directly.",
    specs: {
      Model: "TYSH-TYS7",
      Display: "4.0-inch Color IPS Touch Screen",
      Connectivity: "Tuya WiFi 2.4GHz",
      "Unlock Methods": "Face, Palm, Screen Touch, Fingerprint, Passcode, Card, Key",
      Battery: "4200mAh Rechargeable Lithium",
      Mortise: "6068 Multi-point Mortise",
    },
    tags: ["Tuya", "Touchscreen Lock", "Video Intercom", "Smart Lock"],
  },
  {
    id: "tysh-ty10-v2",
    title: "Tuya TYSH-TY10-V2 Waterproof Outdoor Smart Lock - WiFi",
    slug: "tysh-ty10-v2-ip68-waterproof-smart-lock",
    category: "Smart Door Locks",
    price_pkr: 17640,
    stock: 40,
    discount_pct: 5,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Weather-Resistant Black",
    image_url:
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80",
    description:
      "Certified IP68 outdoor waterproof and dustproof. Engineered specifically for outdoor gates, villa exterior doors, and harsh rain/sunlight environments. Works with Alexa.",
    specs: {
      Model: "TYSH-TY10-V2",
      Protection: "IP68 Waterproof & Dustproof (Silicon encapsulated circuits)",
      "Unlock Methods": "Alexa Voice, 3D Face ID, Palm Vein, Fingerprint, PIN, Card, App",
      Battery: "5000mAh Extreme Temperature Battery (-25°C to 65°C)",
      Mortise: "6068 / 6085 Stainless Steel",
    },
    tags: ["Tuya", "IP68 Waterproof", "Outdoor Gate Lock", "Alexa", "Smart Lock"],
  },
  {
    id: "tysh-lwt12",
    title: "Tuya TYSH-LWT12 Heavy-Duty Outdoor Gate Smart Lock - WiFi",
    slug: "tysh-lwt12-ip68-outdoor-gate-lock",
    category: "Smart Door Locks",
    price_pkr: 19880,
    stock: 28,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Dark Bronze / Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "IP68 outdoor gate lock with video surveillance and palm vein sensor. Supports 22 global system languages and full integration with Alexa and Google Assistant smart scenes.",
    specs: {
      Model: "TYSH-LWT12",
      "Waterproof Rating": "IP68 Certified",
      Biometrics: "Palm Vein & Face Recognition (Day & Night IR)",
      Battery: "5000mAh Rechargeable Lithium",
      Mortise: "6068 / 6085 Mortise",
    },
    tags: ["Tuya", "IP68", "Gate Lock", "Palm Vein", "Smart Lock"],
  },
  {
    id: "tysh-lwt13",
    title: "Tuya TYSH-LWT13 Panoramic Triple-Camera Smart Lock - WiFi",
    slug: "tysh-lwt13-panoramic-3-cameras-smart-lock",
    category: "Smart Door Locks",
    price_pkr: 21000,
    stock: 18,
    discount_pct: 0,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Matte Black",
    image_url:
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80",
    description:
      "Triple-camera system: features front, downward package camera, and indoor panoramic view. 2 independent lithium batteries ensure continuous surveillance even while charging one battery.",
    specs: {
      Model: "TYSH-LWT13",
      Cameras: "3 Dedicated HD Cameras (Face ID, Package Cam, Indoor Monitor)",
      Battery: "Dual 3500mAh Batteries (7000mAh combined)",
      Languages: "21 Voice Prompt Languages",
      Mortise: "6068 Standard Lock Body",
    },
    tags: ["Tuya", "3 Cameras", "Package Detection", "Smart Lock", "Surveillance"],
  },
  {
    id: "tysh-tt01",
    title: "Tuya TYSH-TT01 Biometric Lever Handle Smart Lock - TTLock/BLE",
    slug: "tysh-tt01-biometric-handle-smart-lock",
    category: "Smart Door Locks",
    price_pkr: 5320,
    stock: 120,
    discount_pct: 10,
    rating: 4.7,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Satin Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Affordable and highly reliable biometric handle lock for interior rooms, rental properties, and apartments. Compatible with TTLock and Tuya Bluetooth, supporting e-Keys, PINs, and IC cards.",
    specs: {
      Model: "TYSH-TT01",
      "Unlock Methods": "TTLock / Tuya App, Fingerprint, Passcode, IC Card, Key",
      Power: "4x AAA Alkaline Batteries (Over 12 months lifespan)",
      "Handle Direction": "Free reversible left/right handle",
      Mortise: "Single Latch 60/70mm or 5050 Mortise",
    },
    tags: ["Tuya", "TTLock", "Handle Lock", "Rental Apartment", "Biometric Lock"],
  },
  {
    id: "tysh-lx8",
    title: "Tuya TYSH-LX8 Biometric Lever Handle Smart Lock - Zigbee 3.0",
    slug: "tysh-lx8-handle-smart-lock",
    category: "Smart Door Locks",
    price_pkr: 7280,
    stock: 75,
    discount_pct: 5,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Red Bronze / Obsidian Black",
    image_url:
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80",
    description:
      "Classic lever handle smart lock with embedded semiconductor fingerprint sensor directly in the handle grip. One-step touch and unlock in less than 0.3 seconds.",
    specs: {
      Model: "TYSH-LX8",
      Connectivity: "Tuya WiFi or Zigbee 3.0",
      "Unlock Methods": "Fingerprint, Passcode, IC Card, App, Key",
      Battery: "4x AA Batteries with Micro-USB / Type-C emergency power",
      Mortise: "6068 Standard Mortise",
    },
    tags: ["Tuya", "Lever Lock", "Zigbee", "WiFi", "Smart Lock"],
  },
  {
    id: "tysh-tw01",
    title: "Tuya TYSH-TW01 Waterproof Biometric Handle Smart Lock - WiFi",
    slug: "tysh-tw01-cnc-waterproof-handle-lock",
    category: "Smart Door Locks",
    price_pkr: 8400,
    stock: 60,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Space Gray",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "IPX5 water-resistant smart handle lock with CNC aluminum alloy body. Ideal for exterior doors with porch cover and balcony access points.",
    specs: {
      Model: "TYSH-TW01",
      "Water Resistance": "IPX5 Weatherproof",
      Construction: "Aviation CNC Aluminum",
      Battery: "4x AAA Batteries",
      Mortise: "5050 / 6068 Multi-type Compatible",
    },
    tags: ["Tuya", "CNC Handle", "IPX5", "Waterproof", "Smart Lock"],
  },
  {
    id: "tysh-lwd18",
    title: "Tuya TYSH-LWD18 Narrow Stile Sliding Door Smart Lock - WiFi",
    slug: "tysh-lwd18-ip68-sliding-door-lock",
    category: "Smart Door Locks",
    price_pkr: 18760,
    stock: 35,
    discount_pct: 5,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Slim Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Ultra-slim 35mm profile engineered for aluminum frame glass patio doors, sliding doors, and narrow stile profiles. Full IP68 waterproof rating with video camera and palm vein unlock.",
    specs: {
      Model: "TYSH-LWD18",
      "Door Compatibility": "Narrow Stile Aluminum, Sliding Glass, Swing Patio Doors",
      "Profile Width": "35mm Ultra-Slim Body",
      Protection: "IP68 Waterproof & UV Resistant",
      Battery: "4800mAh Rechargeable Lithium",
      Mortise: "3585 / 2885 Hook Mortise",
    },
    tags: ["Tuya", "Sliding Door", "Narrow Stile", "IP68", "Patio Lock"],
  },
  {
    id: "tysh-lwd30",
    title: "Tuya TYSH-LWD30 Dual-Sided Biometric Sliding Door Lock - WiFi",
    slug: "tysh-lwd30-dual-sided-sliding-door-lock",
    category: "Smart Door Locks",
    price_pkr: 45640,
    stock: 15,
    discount_pct: 12,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Anodized Black",
    image_url:
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80",
    description:
      "Dual-sided security: 3D face recognition, biometric fingerprint, and passcode keypad on BOTH the exterior and interior panels. Prevents unauthorized exit or reaching through glass to open.",
    specs: {
      Model: "TYSH-LWD30",
      "Dual Verification": "Double Face Recognition & Double Keypad (Inside & Outside)",
      Protection: "IP68 Completely Submersible Sealed",
      Battery: "4000mAh High Density Lithium",
      Mortise: "3585 Hook Lock Body",
    },
    tags: ["Tuya", "Dual-Sided", "High Security", "Sliding Door", "Face ID"],
  },
  {
    id: "tysh-lbg11",
    title: "Tuya TYSH-LBG11 Frameless Glass Door Smart Lock - WiFi",
    slug: "tysh-lbg11-frameless-glass-door-lock",
    category: "Smart Door Locks",
    price_pkr: 12880,
    stock: 45,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Mirror Black & Chrome",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Designed for commercial offices and retail stores with 10-12mm frameless glass doors. No drilling required; clamps securely onto the glass leaf. Supports 3D face unlock, fingerprint, and Tuya WiFi attendance logs.",
    specs: {
      Model: "TYSH-LBG11",
      Installation: "Drill-free Clamp for 10-12mm Glass",
      "Tongue Type": "Dual Hook Tongue (Single/Double Glass Door)",
      "Unlock Methods": "Face ID, Fingerprint, Password, IC Card, Tuya App",
      Battery: "2000mAh Lithium Rechargeable",
    },
    tags: ["Tuya", "Glass Door", "Office Lock", "Commercial", "No Drill"],
  },
  {
    id: "tysh-lwn17",
    title: "Tuya TYSH-LWN17 Electric Rim Gate Smart Lock - WiFi",
    slug: "tysh-lwn17-smart-rim-lock",
    category: "Smart Door Locks",
    price_pkr: 7840,
    stock: 55,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Steel Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Surface-mount smart rim lock with double fingerprint reader and RFID card sensor on both sides of the door. Perfect for iron gates, security grilles, and wooden doors.",
    specs: {
      Model: "TYSH-LWN17",
      Type: "Surface Mount Smart Rim Lock",
      Verification: "Double Fingerprint & Double Card Reader",
      Battery: "4x AA Batteries (with DC 12V external power support)",
      Languages: "13 Voice Languages",
    },
    tags: ["Tuya", "Rim Lock", "Gate Lock", "Double Fingerprint", "Surface Mount"],
  },
  {
    id: "tysh-lc02",
    title: "Tuya TYSH-LC02 Biometric Fingerprint Padlock - Bluetooth",
    slug: "tysh-lc02-smart-biometric-padlock",
    category: "Smart Door Locks",
    price_pkr: 2100,
    stock: 150,
    discount_pct: 0,
    rating: 4.7,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Gunmetal Gray",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Compact, heavy-duty smart padlock made of forged zinc alloy with stainless steel shackle. Fast 0.5s fingerprint sensor, Bluetooth app authorization, and emergency Morse code unlock.",
    specs: {
      Model: "TYSH-LC02",
      Shackle: "Hardened Stainless Steel Anti-Cut Shackle",
      Protection: "IP65 Weatherproof",
      Battery: "150mAh Lithium Rechargeable (Over 2,000 unlocks per charge)",
    },
    tags: ["Tuya", "Padlock", "Fingerprint Padlock", "IP65", "Luggage & Shed"],
  },

  // ==========================================
  // SECTION 2: TUYA SMART CONTROL PANELS (Pages 30–32)
  // ==========================================
  {
    id: "tysh-ccs1",
    title: "Tuya TYSH-CCS1 4-Inch Central Control Panel - Zigbee 3.0",
    slug: "tysh-ccs1-4inch-smart-control-panel",
    category: "Smart Control Panels",
    price_pkr: 20160,
    stock: 40,
    discount_pct: 0,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Snow White / Obsidian Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    ],
    description:
      "All-in-one wall-mounted smart central control console. Fits standard 86x86mm wall switch boxes. Features an ultra-crisp 4-inch touch screen, built-in Zigbee 3.0 gateway hub, Alexa voice control, and unified scene switching for all smart lights, curtains, and locks.",
    specs: {
      Model: "TYSH-CCS1",
      Screen: "4.0-inch 480x480 Capacitive Touch IPS Display",
      "Operating System": "Linux Smart Home OS",
      Gateway: "Built-in Zigbee 3.0 Gateway Hub (Connects 100+ sub-devices)",
      "Voice Control": "Built-in Amazon Alexa Voice Assistant",
      Connectivity: "WiFi 2.4GHz + Ethernet RJ45 + Zigbee 3.0",
      "Power Supply": "100-240V AC 50/60Hz (Standard 86 switch box)",
    },
    tags: [
      "Tuya",
      "Control Panel",
      "Zigbee Gateway",
      "Alexa Built-in",
      "Touch Screen",
      "Smart Home",
    ],
  },
  {
    id: "tysh-cs14",
    title: "Tuya TYSH-CS14 7-Inch Multi-Relay Control Panel - Zigbee 3.0",
    slug: "tysh-cs14-7inch-smart-control-panel",
    category: "Smart Control Panels",
    price_pkr: 41440,
    stock: 25,
    discount_pct: 5,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Brushed Black Alloy",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Premium 7-inch widescreen smart home command center with 4 external high-gain antennas for unmatched whole-villa wireless coverage. Includes 2 built-in 10A physical relays to control high-load light circuits directly from the wall.",
    specs: {
      Model: "TYSH-CS14",
      Screen: "7.0-inch IPS High Definition (1024x600)",
      "Wireless Range": "4x High-Gain Antennas (Zigbee 3.0 + BLE Mesh + WiFi)",
      "Built-in Relays": "2x 10A Lighting Relays (2000W max)",
      Audio: "Built-in Dual Microphone Array & Hi-Fi Speaker",
      Power: "100-240V AC",
    },
    tags: ["Tuya", "7-inch Panel", "Smart Control", "Zigbee Hub", "Relay Output"],
  },
  {
    id: "tysh-ccs7",
    title: "Tuya TYSH-CCS7 5-Inch Voice Assistant Control Panel - WiFi",
    slug: "tysh-ccs7-5inch-smart-control-panel",
    category: "Smart Control Panels",
    price_pkr: 27720,
    stock: 30,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Matte Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Sleek 5-inch landscape form factor (127x72.5mm). Built-in Zigbee gateway, direct Alexa voice recognition, intercom calling between rooms, and complete status monitoring for climate and security sensors.",
    specs: {
      Model: "TYSH-CCS7",
      Screen: "5.0-inch IPS Touch Panel",
      Features: "Alexa Voice, Zigbee Hub, Room-to-Room Intercom",
      Network: "WiFi 2.4GHz + Zigbee 3.0 + BLE",
      Installation: "Fits Double 86 Box or US Standard Junction Box",
    },
    tags: ["Tuya", "5-inch Screen", "Alexa", "Zigbee Hub", "Smart Home Console"],
  },
  {
    id: "tysh-ccs3c",
    title: "Tuya TYSH-CCS3C 7-Inch Multimedia Smart Console - WiFi",
    slug: "tysh-ccs3c-7inch-smart-panel-google-play-8-speakers",
    category: "Smart Control Panels",
    price_pkr: 52360,
    stock: 15,
    discount_pct: 0,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Anodized Silver / Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Flagship Android OS wall panel with native Google Play Store support. Allows installing Spotify, YouTube Music, and home automation apps. Features multi-room amplifier output capable of driving up to 8 ceiling speakers.",
    specs: {
      Model: "TYSH-CCS3C",
      OS: "Android Smart OS with Google Play Store",
      "Audio Amplifier": "8-Channel Multi-Room Speaker Output (8x 25W RMS)",
      Screen: "7.0-inch IPS Multi-Touch (1280x800)",
      Connectivity: "Dual-Band WiFi (2.4G/5G) + RJ45 Gigabit + Zigbee 3.0",
    },
    tags: ["Tuya", "Google Play", "Multi-Room Audio", "8 Speakers", "7-inch Panel"],
  },
  {
    id: "tysh-ccs5p",
    title: "Tuya TYSH-CCS5P 10-Inch Flagship Smart Audio Console - WiFi",
    slug: "tysh-ccs5p-10inch-flagship-smart-console",
    category: "Smart Control Panels",
    price_pkr: 71400,
    stock: 12,
    discount_pct: 8,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Titanium Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "The ultimate whole-villa automation and entertainment console. 10.1-inch edge-to-edge glass display with Android Google Play system, built-in 8-speaker zone amplifier, Zigbee 3.0 gateway, and smart video intercom hub.",
    specs: {
      Model: "TYSH-CCS5P",
      Screen: "10.1-inch Full HD 1920x1200 IPS Display",
      System: "Octa-Core Android OS with Google Play Services",
      Audio: "8-Zone Multi-Channel Hi-Fi Digital Power Amplifier",
      Intercom: "2-Way HD Video Calling with Doorbell & Surveillance Cameras",
      Dimensions: "297mm x 162mm Luxury Wall Frame",
    },
    tags: ["Tuya", "10-inch Console", "Flagship", "Google Play", "Villa Automation"],
  },
  {
    id: "tysh-ccs6",
    title: "Tuya TYSH-CCS6 12-Inch Ultra-Wide Control Console - WiFi",
    slug: "tysh-ccs6-12inch-executive-smart-panel",
    category: "Smart Control Panels",
    price_pkr: 73640,
    stock: 10,
    discount_pct: 10,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Billet Aluminum Frame",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Cinema-ratio ultra-wide 12-inch panoramic smart touch panel (354x143mm) machined from solid aviation aluminum. Features dual speaker output, Ethernet port, Zigbee hub, and simultaneous split-screen controls.",
    specs: {
      Model: "TYSH-CCS6",
      Screen: "12.0-inch Ultra-Wide Panoramic Touch Screen",
      Frame: "Precision Aluminum Alloy Bezel",
      Audio: "Integrated Dual Hi-Fi Speakers Output",
      Connectivity: "Gigabit LAN, Dual-Band WiFi, Zigbee 3.0, Bluetooth Sigmesh",
    },
    tags: ["Tuya", "12-inch Panel", "Ultra-Wide", "Executive", "Smart Home Console"],
  },
  {
    id: "tysh-ccs9",
    title: "Tuya TYSH-CCS9 3.5-Inch Smart Panel with IR Blaster - WiFi",
    slug: "tysh-ccs9-3-5inch-smart-panel-ir-blaster",
    category: "Smart Control Panels",
    price_pkr: 14700,
    stock: 45,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Pearl White / Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Replaces standard 86-type light switches. Features a 3.5-inch color touch screen, 3 physical 10A light relays, integrated Bluetooth Sigmesh gateway, and a 360-degree infrared remote blaster for controlling ACs and TVs.",
    specs: {
      Model: "TYSH-CCS9",
      Screen: "3.5-inch Touch Screen (86x86mm standard box)",
      Relays: "3x Built-in 10A Lighting Relays",
      "IR Remote": "Built-in 360° Infrared Air Conditioner / TV Controller",
      "Mesh Hub": "Integrated Bluetooth Sigmesh Gateway",
    },
    tags: ["Tuya", "3.5-inch", "IR Blaster", "3 Relays", "Smart Switch Panel"],
  },

  // ==========================================
  // SECTION 3: TUYA SMART SWITCHES (Pages 33–38)
  // ==========================================
  {
    id: "tysh-z0426",
    title: "Tuya TYSH-Z0426 4-Way Smart Screen Switch - Zigbee 3.0",
    slug: "tysh-z0426-4way-zigbee-smart-screen-switch",
    category: "Smart Switches",
    price_pkr: 8680,
    stock: 50,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Midnight Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Next-generation wall switch featuring a 3.5-inch high-res LCD screen with a millimeter-wave human body radar sensor that wakes the screen when someone approaches. Controls 4 independent 500W light channels plus smart scenes.",
    specs: {
      Model: "TYSH-Z0426",
      Screen: "3.5-inch 320x480 IPS Touch LCD",
      Sensor: "24GHz Millimeter-Wave Radar Human Presence Sensor",
      Channels: "4x 500W Lighting Relays (2000W total)",
      Interface: "RS485 + Zigbee 3.0 Mesh Protocol",
      Wiring: "Neutral + Live Wire Required",
    },
    tags: ["Tuya", "Screen Switch", "Radar Presence", "Zigbee 3.0", "4-Way Switch"],
  },
  {
    id: "tysh-z0446",
    title: "Tuya TYSH-Z0446 4-Gang Wireless Scene Switch - Zigbee 3.0",
    slug: "tysh-z0446-4gang-zigbee-scene-switch",
    category: "Smart Switches",
    price_pkr: 5600,
    stock: 80,
    discount_pct: 0,
    rating: 4.7,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Matte White",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Wire-free portable battery-operated scene remote. 4 tactile click buttons, each supporting Single Click, Double Click, and Long Press actions to trigger 12 custom automation scenarios.",
    specs: {
      Model: "TYSH-Z0446",
      Buttons: "4 Micro-switch Tactile Buttons (12 Actions)",
      Protocol: "Zigbee 3.0 (Low power)",
      Battery: "CR2430 Button Cell (Over 2 years battery life)",
    },
    tags: ["Tuya", "Scene Switch", "Wireless Button", "Zigbee 3.0"],
  },
  {
    id: "tysh-z03",
    title: "Tuya TYSH-Z03 Rotary Dimmer Switch with Circular LCD - Zigbee 3.0",
    slug: "tysh-z03-smart-rotary-dimmer-switch",
    category: "Smart Switches",
    price_pkr: 7700,
    stock: 45,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Space Gray Rotary Knob",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Precision CNC milled rotary aluminum knob with central round LCD display. Stepless dimming from 1% to 100% and CCT color temperature adjustment for spotlights, chandeliers, and magnetic track lights.",
    specs: {
      Model: "TYSH-Z03",
      Screen: "1.3-inch Circular TFT Status Display",
      Control: "Stepless Rotary Knob + Center Push Button",
      Protocol: "Zigbee 3.0",
      "Dimming Type": "Trailing-Edge Phase Dimming / 0-10V / DALI",
    },
    tags: ["Tuya", "Rotary Dimmer", "Circular LCD", "Knob Switch", "Zigbee"],
  },
  {
    id: "tysh-1114",
    title: "Tuya TYSH-1114 1-Gang Luxury Touch Switch - Matter/WiFi",
    slug: "tysh-1114-1gang-touch-smart-switch",
    category: "Smart Switches",
    price_pkr: 1350,
    stock: 200,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Tempered Glass White / Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Standard 86x86mm tempered glass touch switch. Scratch-resistant, fireproof V0 ABS enclosure, soft LED backlight. Supports voice control via Alexa & Google Home.",
    specs: {
      Model: "TYSH-1114",
      Gangs: "1 Gang (Single Live or Neutral+Live Compatible)",
      "Max Load": "1000W / Gang (16A max)",
      Faceplate: "Anti-fingerprint Tempered Glass",
      Voltage: "100V - 240V AC 50/60Hz",
    },
    tags: ["Tuya", "Smart Switch", "1-Gang", "Glass Touch", "Alexa", "Google Home"],
  },
  {
    id: "tysh-1214",
    title: "Tuya TYSH-1214 2-Gang Luxury Touch Switch - Matter/WiFi",
    slug: "tysh-1214-2gang-touch-smart-switch",
    category: "Smart Switches",
    price_pkr: 1480,
    stock: 180,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Tempered Glass White / Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "2-Gang touch smart switch with independent relay control. Set timers, schedules, and countdowns in the Tuya app.",
    specs: {
      Model: "TYSH-1214",
      Gangs: "2 Gangs",
      "Max Load": "600W / Gang",
      Protocol: "WiFi 2.4GHz / Matter over WiFi",
    },
    tags: ["Tuya", "Smart Switch", "2-Gang", "WiFi", "Matter"],
  },
  {
    id: "tysh-1314",
    title: "Tuya TYSH-1314 3-Gang Luxury Touch Switch - Matter/WiFi",
    slug: "tysh-1314-3gang-touch-smart-switch",
    category: "Smart Switches",
    price_pkr: 1570,
    stock: 160,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Tempered Glass White / Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "3-Gang touch wall switch with individual LED status indicators. Supports grouping and room scenes.",
    specs: {
      Model: "TYSH-1314",
      Gangs: "3 Gangs",
      "Max Load": "500W / Gang",
      Voltage: "100-240V AC",
    },
    tags: ["Tuya", "Smart Switch", "3-Gang", "WiFi"],
  },
  {
    id: "tysh-1414",
    title: "Tuya TYSH-1414 4-Gang Luxury Touch Switch - Matter/WiFi",
    slug: "tysh-1414-4gang-touch-smart-switch",
    category: "Smart Switches",
    price_pkr: 1650,
    stock: 140,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Tempered Glass White / Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "4-Gang smart switch panel for high density lighting zones in living rooms and corridors.",
    specs: {
      Model: "TYSH-1414",
      Gangs: "4 Gangs",
      "Max Load": "400W / Gang",
    },
    tags: ["Tuya", "Smart Switch", "4-Gang", "WiFi"],
  },
  {
    id: "tysh-b23",
    title: "Tuya TYSH-B23 40A Geyser & Boiler Smart Switch - WiFi",
    slug: "tysh-b23-40a-smart-geyser-switch",
    category: "Smart Switches",
    price_pkr: 1900,
    stock: 95,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Crystal Glass Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Heavy duty 40A / 8000W rated relay engineered specifically for electric water heaters, geysers, boilers, and high-tonnage air conditioners. Features timer scheduling and surge protection.",
    specs: {
      Model: "TYSH-B23",
      "Max Current": "40A Heavy Duty Relay",
      "Max Power": "8000W Resistive Load",
      Safety: "Surge Protection, Overload Auto-Trip, Flame-retardant Glass",
      Wiring: "Neutral + Live Required",
    },
    tags: ["Tuya", "Geyser Switch", "40A", "Boiler Switch", "High Power", "Water Heater"],
  },
  {
    id: "tysh-f23",
    title: "Tuya TYSH-F23 Stepless Ceiling Fan Controller Switch - WiFi",
    slug: "tysh-f23-smart-fan-speed-controller",
    category: "Smart Switches",
    price_pkr: 1930,
    stock: 85,
    discount_pct: 0,
    rating: 4.7,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Tempered Glass White",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Smart 4-speed fan dimmer with touch capacitive steps and Tuya app speed control. Voice adjust speed via Alexa or Google Assistant.",
    specs: {
      Model: "TYSH-F23",
      "Speed Steps": "4 Preset Speeds (Off, Low, Med, High)",
      "Max Load": "400W Fan Motor Load",
    },
    tags: ["Tuya", "Fan Switch", "Fan Controller", "Smart Switch"],
  },
  {
    id: "tysh-c23",
    title: "Tuya TYSH-C23 Motorized Curtain & Shutter Touch Switch - WiFi",
    slug: "tysh-c23-smart-curtain-touch-switch",
    category: "Smart Switches",
    price_pkr: 1900,
    stock: 90,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Glass White / Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Dedicated touch switch for motorized curtains and motorized roller shutters. Features Open, Pause, and Close capacitive touch buttons with accurate percentage calibration.",
    specs: {
      Model: "TYSH-C23",
      Controls: "Open, Pause, Close, Percentage Opening (0-100%)",
      Load: "600W Motor Load",
    },
    tags: ["Tuya", "Curtain Switch", "Roller Shutter", "Smart Switch"],
  },
  {
    id: "tysh-1ch",
    title: "Tuya TYSH-1CH 16A Mini Breaker Switch Relay Module - WiFi",
    slug: "tysh-1ch-mini-smart-switch-module-16a",
    category: "Smart Switches",
    price_pkr: 920,
    stock: 250,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Compact White Housing",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Ultra-compact smart relay module that fits invisibly behind traditional wall switches inside standard junction boxes. Converts existing manual switches into smart switches without rewiring.",
    specs: {
      Model: "TYSH-1CH",
      Dimensions: "39.2 x 39.2 x 18 mm (Fits all wall boxes)",
      Rating: "16A 3680W Max Load",
      Wiring: "Dual-way 2-way switch control supported",
    },
    tags: ["Tuya", "Mini Relay", "Switch Module", "16A", "Hidden Relay"],
  },
  {
    id: "tysh-l1ch",
    title: "Tuya TYSH-L1CH No-Neutral Mini Switch Relay Module - Zigbee 3.0",
    slug: "tysh-l1ch-no-neutral-mini-switch-module",
    category: "Smart Switches",
    price_pkr: 1120,
    stock: 180,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Compact White Housing",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Single-live wire smart module requiring NO neutral wire. Perfect for retrofitting older homes and apartments without pulling new wiring.",
    specs: {
      Model: "TYSH-L1CH",
      Wiring: "Single Live Wire Only (No Neutral Required)",
      Capacitor: "Includes anti-flicker safety capacitor",
    },
    tags: ["Tuya", "No Neutral", "Single Live", "Switch Module"],
  },

  // ==========================================
  // SECTION 4: TUYA SMART SOCKETS & PLUGS (Pages 39–41)
  // ==========================================
  {
    id: "tysh-us10",
    title: "Tuya TYSH-US10 70W GaN Fast Charger Smart Socket - WiFi",
    slug: "tysh-us10-70w-gan-super-charger-wall-socket",
    category: "Smart Sockets & Plugs",
    price_pkr: 3840,
    stock: 75,
    discount_pct: 5,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Matte Black / Clean White",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Revolutionary wall socket featuring a built-in 70W GaN (Gallium Nitride) ultra-fast laptop & smartphone charger directly on the wall plate. Includes 1x 70W USB-C PD3.0 port + 1x USB-A QC3.0 port alongside a 16A universal AC socket.",
    specs: {
      Model: "TYSH-US10",
      "USB-C Output": "70W Max (PD3.0 / PPS / QC4+ / Super Fast Charge)",
      "USB-A Output": "30W Max (QC3.0 / FCP / AFC)",
      "AC Socket": "16A 250V Universal Grounded Socket (UK/EU/US compatible)",
      Technology: "GaN III High Efficiency Silicon",
      Safety: "Child Safety Protection Shutters + Overheat Cut-off",
    },
    tags: ["Tuya", "70W GaN", "Super Charger", "USB-C PD", "Wall Socket", "Fast Charging"],
  },
  {
    id: "tysh-us11",
    title: "Tuya TYSH-US11 70W GaN Socket with Touch Light Switch - WiFi",
    slug: "tysh-us11-70w-gan-socket-with-touch-switch",
    category: "Smart Sockets & Plugs",
    price_pkr: 5740,
    stock: 45,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Tempered Glass Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Combo unit: 70W GaN laptop fast charging port + 16A Universal AC socket + 1-gang smart light switch all integrated into a single standard 86mm wall plate.",
    specs: {
      Model: "TYSH-US11",
      Components: "70W GaN USB-C/A + 16A Universal Socket + Smart Touch Switch",
      Connectivity: "WiFi 2.4GHz + Tuya Smart App",
      Panel: "Seamless Tempered Glass Faceplate",
    },
    tags: ["Tuya", "70W GaN", "Socket Switch Combo", "USB-C", "Smart Home"],
  },
  {
    id: "tysh-ps01",
    title: "Tuya TYSH-PS01 4-Outlet Surge Protected Power Strip - WiFi",
    slug: "tysh-ps01-smart-power-strip-4-outlets-4-usb",
    category: "Smart Sockets & Plugs",
    price_pkr: 4620,
    stock: 65,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Fireproof Pure White",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Heavy-duty smart extension lead. 4 individual smart AC outlets that can be switched on/off independently via Tuya app or Alexa voice commands, plus 4 USB fast charging ports (including Type-C).",
    specs: {
      Model: "TYSH-PS01",
      Outlets: "4x Independent Smart AC Outlets + 4x USB Ports",
      Rating: "16A 3500W Max Load",
      Protection: "1700 Joules Surge & Lightning Protection",
      "Cable Length": "1.8 Meter Heavy Duty Pure Copper Cord",
    },
    tags: ["Tuya", "Power Strip", "Surge Protector", "Independent Control", "USB-C"],
  },
  {
    id: "tysh-us02",
    title: "Tuya TYSH-US02 16A Power Monitoring Smart Plug - WiFi",
    slug: "tysh-us02-16a-smart-plug-energy-meter",
    category: "Smart Sockets & Plugs",
    price_pkr: 900,
    stock: 300,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Gloss White",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Compact smart plug with real-time kWh electricity monitoring. Track energy consumption of refrigerators, heaters, and home appliances in the Tuya app with graphs and exportable logs.",
    specs: {
      Model: "TYSH-US02",
      Rating: "16A 3680W Max Load",
      "Energy Monitoring": "Real-time Voltage, Current, Power (W), Daily/Monthly kWh",
      Protocol: "WiFi 2.4GHz / Matter Compatible",
    },
    tags: ["Tuya", "Smart Plug", "Energy Monitor", "16A", "Matter", "Power Meter"],
  },

  // ==========================================
  // SECTION 5: SMART CURTAIN SYSTEMS (Pages 41–47)
  // ==========================================
  {
    id: "tysh-curtain-combo-3m",
    title: "Tuya TYSH-M32 3.2M Motorized Curtain Track Set - WiFi",
    slug: "smart-curtain-motorized-track-set-3-2m",
    category: "Smart Curtain Systems",
    price_pkr: 10640,
    stock: 35,
    discount_pct: 0,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Anodized White Track",
    image_url:
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80",
    description:
      "Complete motorized curtain package including 3.2-meter modular high-load aluminum track, steel-reinforced drive belt, master transmission gearboxes, silent runners, ceiling & wall brackets, wireless RF remote, and a Tuya Smart quiet curtain motor.",
    specs: {
      Length: "3.2 Meters (Modular pieces: 1m + 1m + 0.5m + 0.2m + 0.1m)",
      "Curtain Motor": "TYSH-MW01 Heavy Duty Silent Motor (<30dB)",
      "Load Capacity": "Up to 50KG Fabric Weight",
      Operation: "App Control, Touch Pull-to-Start, RF Remote, Manual when power off",
      "Opening Style": "Center Double Open or One-Way Side Open",
    },
    tags: ["Tuya", "Motorized Curtain", "Electric Curtain Track", "Quiet Motor", "Smart Curtain"],
  },
  {
    id: "tysh-curtain-combo-5m",
    title: "Tuya TYSH-M52 5.2M Motorized Curtain Track Set - WiFi",
    slug: "smart-curtain-motorized-track-set-5-2m",
    category: "Smart Curtain Systems",
    price_pkr: 14560,
    stock: 25,
    discount_pct: 0,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Anodized White Track",
    image_url:
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80",
    description:
      "5.2-Meter heavy duty smart curtain track set for large master bedrooms and living room glass walls. Full automation with Tuya schedules and sunrise/sunset tracking.",
    specs: {
      Length: "5.2 Meters Total Track Assembly",
      "Load Capacity": "Up to 50KG Curtain Load",
      Motor: "Tuya AC 100-240V Silent Motor Included",
    },
    tags: ["Tuya", "Curtain Track 5M", "Motorized Drapery", "Smart Home"],
  },
  {
    id: "tysh-curtain-s-type-4m",
    title: "Tuya TYSH-MS42 4.2M S-Type Wave Fold Curtain Track - WiFi",
    slug: "smart-curtain-s-type-ripple-wave-track-4-2m",
    category: "Smart Curtain Systems",
    price_pkr: 15400,
    stock: 20,
    discount_pct: 5,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Luxury Matte White",
    image_url:
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80",
    description:
      "Luxury architectural S-Type (Wave Fold / Ripple Fold) motorized curtain system. Keeps uniform, elegant fabric folds in high-end villas and penthouses.",
    specs: {
      "Track Style": "S-Type Wave Ripple Fold",
      Length: "4.2 Meters",
      Load: "50KG Maximum Drapery Load",
      Control: "Tuya WiFi / Zigbee / Matter + RF Remote",
    },
    tags: ["Tuya", "S-Type Track", "Wave Fold", "Ripple Fold", "Luxury Curtains"],
  },
  {
    id: "tysh-mw21",
    title: "Tuya TYSH-MW21 Universal Rechargeable Curtain Robot Motor - Bluetooth",
    slug: "tysh-mw21-universal-curtain-robot-motor",
    category: "Smart Curtain Systems",
    price_pkr: 9240,
    stock: 60,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Clean White",
    image_url:
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80",
    description:
      "No track replacement needed: hangs directly onto your existing curtain rod (Roman rod, U-rail, or T-rail). Powered by an internal 4000mAh lithium battery that lasts up to 6 months per charge, with optional solar panel attachment.",
    specs: {
      Model: "TYSH-MW21",
      Compatibility: "Universal (Roman Rod 16-38mm, U-Rail, T-Rail)",
      Battery: "4000mAh Rechargeable Lithium",
      "Solar Option": "Type-C Solar Panel Charging Compatible",
      "Max Thrust": "12KG Fabric Weight Pulling Capacity",
    },
    tags: ["Tuya", "Curtain Robot", "Retrofit Motor", "Rechargeable", "Roman Rod"],
  },
  {
    id: "tysh-rb05-10n",
    title: "Tuya TYSH-RB05 10Nm 35mm Roller Blind Tubular Motor - Zigbee 3.0",
    slug: "tysh-rb05-10n-35mm-tubular-roller-motor",
    category: "Smart Curtain Systems",
    price_pkr: 11900,
    stock: 35,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Silver Steel Tube",
    image_url:
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80",
    description:
      "High-torque 35mm tubular motor for heavy blackout roller blinds, zebra blinds, and projection screens up to 40KG. Precision electronic limits set via Tuya App or remote.",
    specs: {
      Model: "TYSH-RB05-10N",
      Diameter: "35mm Tube Diameter",
      Torque: "10Nm High Torque (40KG lifting power)",
      Power: "220V AC 50/60Hz",
    },
    tags: ["Tuya", "Tubular Motor", "Roller Blinds", "Zebra Blinds", "10Nm"],
  },

  // ==========================================
  // SECTION 6: SMART THERMOSTATS & TRV (Pages 48–51)
  // ==========================================
  {
    id: "tysh-st10",
    title: "Tuya TYSH-ST10 Digital Boiler & Floor Heating Thermostat - WiFi",
    slug: "tysh-st10-smart-digital-thermostat",
    category: "Smart Thermostats",
    price_pkr: 4480,
    stock: 70,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Gloss Black / Clean White",
    image_url:
      "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=800&auto=format&fit=crop&q=80",
    description:
      "Weekly programmable smart thermostat with clean backlit display. Controls gas boilers, water floor heating actuators, and electric heaters. Features open-window detection and frost protection.",
    specs: {
      Model: "TYSH-ST10",
      "Current Load": "3A (Water/Boiler) or 16A (Electric Heating)",
      Accuracy: "±0.5°C Temperature Precision",
      Programming: "5+2, 6+1, or 7-Day Weekly Schedules",
      "Voice Compatibility": "Alexa, Google Assistant, Tuya Smart",
    },
    tags: ["Tuya", "Thermostat", "Boiler Heating", "Underfloor Heating", "HVAC"],
  },
  {
    id: "tysh-st19",
    title: "Tuya TYSH-ST19 Luxury Rotary Dial Smart Thermostat - WiFi",
    slug: "tysh-st19-luxury-rotary-smart-thermostat",
    category: "Smart Thermostats",
    price_pkr: 10780,
    stock: 40,
    discount_pct: 5,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Anodized Champagne Gold / Black",
    image_url:
      "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=800&auto=format&fit=crop&q=80",
    description:
      "Flagship luxury dial thermostat with continuous rotary aluminum knob, ambient temperature halo lighting, and integrated humidity display.",
    specs: {
      Model: "TYSH-ST19",
      Display: "Circular Color VA Screen with Ambient Ring",
      Control: "Precision Aluminum Encoder Knob",
      Compatibility: "Gas Boiler, Heat Pump, Underfloor Hydronic Heating",
    },
    tags: ["Tuya", "Luxury Thermostat", "Rotary Dial", "HVAC", "Smart Climate"],
  },
  {
    id: "tysh-sv01",
    title: "Tuya TYSH-SV01 Radiator Thermostatic Valve TRV - Zigbee 3.0",
    slug: "tysh-sv01-tuya-smart-radiator-thermostatic-valve",
    category: "Smart Thermostats",
    price_pkr: 3500,
    stock: 90,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Pure White",
    image_url:
      "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=800&auto=format&fit=crop&q=80",
    description:
      "Replaces traditional manual radiator knobs in minutes. Controls room temperature individually per radiator via Tuya app schedules. Includes Danfoss RA/RAV/RAVL adapters.",
    specs: {
      Model: "TYSH-SV01",
      Adapters: "M30 x 1.5mm, Danfoss RA, RAV, RAVL included",
      Power: "2x 1.5V AA Batteries (Over 1.5 years)",
      Features: "Window Opening Sensor, Anti-Scale Routine, Child Lock",
    },
    tags: ["Tuya", "TRV", "Radiator Valve", "Smart Heating", "Energy Saving"],
  },

  // ==========================================
  // SECTION 7: SMART CIRCUIT BREAKERS (Pages 52–53)
  // ==========================================
  {
    id: "tysh-cb01",
    title: "Tuya TYSH-CB01 1P 63A Energy Monitoring DIN Rail Breaker - WiFi",
    slug: "tysh-cb01-1p-63a-smart-din-rail-breaker",
    category: "Smart Circuit Breakers",
    price_pkr: 2630,
    stock: 100,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Industrial Grey DIN Rail Housing",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "1-Pole 63A DIN Rail mounted smart circuit breaker. Provides remote ON/OFF control of electrical circuits from your phone, timer scheduling, and comprehensive overcurrent, short circuit, and over/undervoltage protection.",
    specs: {
      Model: "TYSH-CB01",
      Poles: "1P Single Phase",
      "Rated Current": "63A (Adjustable 1A-63A in App)",
      Protection: "Overload, Short Circuit, Overvoltage, Undervoltage",
      Metering: "Real-time Voltage (V), Current (A), Power (W), Energy (kWh)",
      Mounting: "Standard 35mm DIN Rail Mount",
    },
    tags: ["Tuya", "Circuit Breaker", "DIN Rail", "Power Metering", "63A", "Distribution Board"],
  },
  {
    id: "tysh-cb03",
    title: "Tuya TYSH-CB03 2P 63A Energy Monitoring DIN Rail Breaker - WiFi",
    slug: "tysh-cb03-2p-63a-smart-circuit-breaker",
    category: "Smart Circuit Breakers",
    price_pkr: 4060,
    stock: 80,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Industrial Grey",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "2-Pole 63A smart breaker for main switchboards. Completely isolates both Live and Neutral conductors with bidirectional real-time electricity consumption and solar generation monitoring.",
    specs: {
      Model: "TYSH-CB03",
      Poles: "2P (L + N Dual Isolation)",
      "Rated Current": "63A (Configurable thresholds)",
      Protocol: "WiFi 2.4GHz / Zigbee 3.0",
    },
    tags: ["Tuya", "2P Breaker", "DIN Rail", "Solar Metering", "Smart DB"],
  },
  {
    id: "tysh-cb07",
    title: "Tuya TYSH-CB07 4P 63A 3-Phase DIN Rail Breaker - WiFi",
    slug: "tysh-cb07-4p-63a-3phase-smart-circuit-breaker",
    category: "Smart Circuit Breakers",
    price_pkr: 10220,
    stock: 30,
    discount_pct: 0,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Industrial White/Grey",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "4-Pole 3-Phase + Neutral industrial grade smart circuit breaker. Real-time phase voltage balance tracking, aggregate kWh monitoring, and automatic trip protection against phase loss, lightning spikes, and motor overloads.",
    specs: {
      Model: "TYSH-CB07",
      Poles: "4P (3-Phase + N)",
      Voltage: "380V - 415V AC 3-Phase",
      "Rated Current": "63A Continuous Industrial Rating",
    },
    tags: ["Tuya", "3-Phase Breaker", "4P", "Industrial Automation", "Factory Power"],
  },
  {
    id: "tysh-cb14",
    title: "Tuya TYSH-CB14 16-Channel Energy Monitoring Smart Breaker - WiFi/RS485",
    slug: "tysh-cb14-16channel-smart-breaker-module",
    category: "Smart Circuit Breakers",
    price_pkr: 17220,
    stock: 20,
    discount_pct: 5,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Modular Gray DB Enclosure",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Compact multi-channel smart energy distribution module: monitors and switches up to 16 individual branch circuits (lights, air conditioners, heaters, kitchen appliances) from a single unified DIN module.",
    specs: {
      Model: "TYSH-CB14",
      Channels: "16 Independent Relay Channels with Metering",
      Communication: "RS485 Modbus + WiFi / Zigbee Hub Link",
      Applications: "Commercial Offices, Villas, Hotels, Server Rooms",
    },
    tags: ["Tuya", "16-Channel", "Multi-Circuit", "Energy Management", "Smart Breaker"],
  },

  // ==========================================
  // SECTION 8: GATEWAYS & TUYA SENSORS (Pages 53–55)
  // ==========================================
  {
    id: "tysh-ah11-m",
    title: "Tuya TYSH-AH11-M Multi-Protocol Smart Hub - Matter/Thread/WiFi",
    slug: "tysh-ah11-m-matter-thread-gateway-hub",
    category: "Gateways",
    price_pkr: 16520,
    stock: 50,
    discount_pct: 0,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Ceramic White",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "The universal bridge for next-generation smart homes. Matter certified: seamlessly bridges all Tuya Zigbee and Bluetooth devices into Apple HomeKit, Google Home, Amazon Alexa, and Samsung SmartThings simultaneously.",
    specs: {
      Model: "TYSH-AH11-M",
      Protocols: "Matter, Thread Mesh, Zigbee 3.0, BLE Mesh, WiFi 2.4GHz",
      Ecosystems: "Apple HomeKit, Google Home, Alexa, SmartThings, Home Assistant",
      Capacity: "Supports up to 128 connected sub-devices",
    },
    tags: ["Tuya", "Matter", "Thread Gateway", "Apple HomeKit", "Universal Gateway"],
  },
  {
    id: "tysh-ah06",
    title: "Tuya TYSH-AH06 Dual Smart Gateway Hub - HomeKit/Zigbee 3.0",
    slug: "tysh-ah06-homekit-zigbee-gateway",
    category: "Gateways",
    price_pkr: 4480,
    stock: 95,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Matte White",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Officially certified Apple HomeKit hub. Automatically exposes connected Tuya Zigbee sensors, switches, and valves into the Apple iOS Home app and Siri.",
    specs: {
      Model: "TYSH-AH06",
      Protocols: "Apple HomeKit Certified + Zigbee 3.0 + Ethernet RJ45",
      Capacity: "100+ Zigbee Devices",
    },
    tags: ["Tuya", "Apple HomeKit", "Siri", "Zigbee 3.0", "Gateway"],
  },
  {
    id: "tysh-ah01",
    title: "Tuya TYSH-AH01 Multi-Mode Mini Gateway Hub - Zigbee 3.0/BLE",
    slug: "tysh-ah01-multi-mode-mini-gateway",
    category: "Gateways",
    price_pkr: 2800,
    stock: 150,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Pure White",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Compact USB-powered multi-mode smart hub. Simultaneously coordinates Zigbee 3.0 sensors and Bluetooth Sigmesh lighting with local scene automation rules that execute even when internet is down.",
    specs: {
      Model: "TYSH-AH01",
      Protocols: "Zigbee 3.0 + BLE 5.0 Sigmesh + WiFi 2.4G",
      Power: "Micro-USB / 5V 1A",
    },
    tags: ["Tuya", "Multi-Mode Gateway", "Zigbee 3.0", "BLE Mesh", "Smart Hub"],
  },
  {
    id: "tysh-aw73",
    title: "Tuya TYSH-AW73 Digital LCD Temperature & Humidity Sensor - WiFi",
    slug: "tysh-aw73-temp-humidity-sensor-lcd",
    category: "Tuya Smart Sensors",
    price_pkr: 2490,
    stock: 120,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "White / Gray Accent",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Features a clean backlit digital LCD showing room temperature, humidity percentage, comfort emoji indicator, and synchronized network clock. Triggers air conditioners and dehumidifiers automatically.",
    specs: {
      Model: "TYSH-AW73",
      "Sensor Chip": "High-Precision Swiss Sensirion Sensor",
      Accuracy: "±0.3°C Temperature, ±3% RH Humidity",
      Battery: "3x AAA Batteries (1+ Year Lifespan)",
    },
    tags: ["Tuya", "Climate Sensor", "Thermometer", "Humidity Sensor", "LCD Clock"],
  },
  {
    id: "tysh-az73",
    title: "Tuya TYSH-AZ73 24GHz Millimeter-Wave Radar Sensor - Zigbee 3.0",
    slug: "tysh-az73-mmwave-human-presence-radar-sensor",
    category: "Tuya Smart Sensors",
    price_pkr: 2940,
    stock: 85,
    discount_pct: 0,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "White Ceiling / Wall Mount",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Unlike traditional PIR motion sensors that turn off lights when you sit still, this 24GHz mmWave radar detects microscopic chest breathing movements. Lights stay on as long as a human is in the room.",
    specs: {
      Model: "TYSH-AZ73",
      Technology: "24GHz FMCW Millimeter-Wave Radar + Ambient Illuminance Lux",
      Detection: "Micro-Motion, Breathing, Static Human Presence",
      Range: "0.3m - 9.0m Adjustable Distance & Sensitivity",
      Power: "USB Type-C 5V Continuous Power",
    },
    tags: ["Tuya", "Human Presence", "mmWave Radar", "24GHz", "Presence Sensor"],
  },
  {
    id: "tysh-aw07",
    title: "Tuya TYSH-AW07 Combustible Gas & LPG Leak Detector - WiFi",
    slug: "tysh-aw07-smart-combustible-gas-detector",
    category: "Tuya Smart Sensors",
    price_pkr: 2400,
    stock: 110,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Pure White",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Early warning safety sensor for methane, LPG, and natural gas leaks in kitchens and boiler rooms. 85dB piercing sounder, visual flashing ring, phone push notifications, and automatic shutoff linkage to gas valves.",
    specs: {
      Model: "TYSH-AW07",
      "Gas Detected": "Methane (CH4), Natural Gas, LPG, Propane",
      "Alarm Level": "7% LEL ± 3% LEL",
      "Siren Volume": "≥85dB at 1 meter",
      Output: "Valve Linkage Output Port (12V Pulse for Solenoid Valve)",
    },
    tags: ["Tuya", "Gas Detector", "Kitchen Safety", "LPG Sensor", "85dB Alarm"],
  },
  {
    id: "tysh-aw54",
    title: "Tuya TYSH-AW54 Photoelectric Smoke & Fire Alarm - WiFi",
    slug: "tysh-aw54-smart-photoelectric-smoke-detector",
    category: "Tuya Smart Sensors",
    price_pkr: 1820,
    stock: 130,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Pure White",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "EN14604 certified optical smoke detector. Detects slow-smoldering and open flames quickly with zero radioactive materials. Sends instant emergency alert notifications to your phone.",
    specs: {
      Model: "TYSH-AW54",
      Sensor: "Dual-Beam Infrared Photoelectric Chamber",
      Standard: "EN14604 European Safety Standard Certified",
      Sound: "≥85dB Fire Siren Alarm at 3m",
      Battery: "CR123A Lithium (Up to 5 years standby)",
    },
    tags: ["Tuya", "Smoke Alarm", "Fire Detector", "Photoelectric", "EN14604"],
  },
  {
    id: "tysh-aw77",
    title: "Tuya TYSH-AW77 Overflow & Flood Water Leak Sensor - WiFi",
    slug: "tysh-aw77-smart-water-leak-sensor",
    category: "Tuya Smart Sensors",
    price_pkr: 1200,
    stock: 140,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Waterproof White",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Place near water heaters, kitchen sinks, washing machines, and basements. Dual gold-plated sensor pins detect standing water and immediately shut off the main motorized water valve.",
    specs: {
      Model: "TYSH-AW77",
      Waterproofing: "IP67 Submersible Sealed",
      Battery: "CR2032 (Over 2 years battery life)",
      Linkage: "Auto-triggers TYSH-WT11 water valve shutoff",
    },
    tags: ["Tuya", "Water Leak", "Flood Detector", "IP67", "Smart Sensor"],
  },
  {
    id: "tysh-wt11",
    title: "Tuya TYSH-WT11 Motorized Pipe Shutoff Valve Manipulator - WiFi",
    slug: "tysh-wt11-motorized-valve-shutoff",
    category: "Tuya Smart Sensors",
    price_pkr: 2720,
    stock: 75,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Industrial Black",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Clamps onto existing manual 1/2-inch, 3/4-inch, or 1-inch quarter-turn lever ball valves without pipe cutting or plumbing modification. Shuts off gas or water automatically when leak sensors trigger.",
    specs: {
      Model: "TYSH-WT11",
      Installation: "No plumbing cuts; clamps directly on existing lever valve",
      Torque: "30-60 kg.cm Powerful Gearmotor",
      Override: "Manual pull-ring clutch for emergency manual shutoff",
      Power: "12V DC 1A Adapter Included",
    },
    tags: ["Tuya", "Valve Controller", "Water Shutoff", "Gas Shutoff", "Emergency Valve"],
  },
  {
    id: "tysh-aw30",
    title: "Tuya TYSH-AW30 Ultrasonic Wireless Tank Level Sensor - WiFi",
    slug: "tysh-aw30-ultrasonic-water-tank-level-detector",
    category: "Tuya Smart Sensors",
    price_pkr: 7140,
    stock: 40,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Weatherproof Outdoor Gray",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Monitors water level in rooftop water tanks, underground cisterns, and diesel tanks without touching liquid. Sends real-time percentage and high/low level alerts to your phone.",
    specs: {
      Model: "TYSH-AW30",
      "Measuring Method": "Non-contact Ultrasonic Depth Echo",
      Range: "0.1 Meter to 15.0 Meters Deep",
      Protection: "IP67 Weatherproof Sensor Head",
    },
    tags: ["Tuya", "Water Level", "Tank Sensor", "Ultrasonic", "IoT Telemetry"],
  },

  // ==========================================
  // SECTION 9: SMART CAMERAS & NVR (Pages 56–57)
  // ==========================================
  {
    id: "tysh-cm06",
    title: "Tuya TYSH-CM06 3MP Dual-Band Security Camera - WiFi",
    slug: "tysh-cm06-3mp-dual-band-window-camera",
    category: "Smart Security Cameras",
    price_pkr: 5040,
    stock: 55,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Matte Black",
    image_url:
      "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&auto=format&fit=crop&q=80",
    description:
      "Specially designed camera with anti-glare suction mount to record through window glass without glare or night-vision reflection. 3MP 2K crystal resolution with dual-band 2.4G/5G WiFi.",
    specs: {
      Model: "TYSH-CM06",
      Resolution: "3MP (2304 x 1296) 2K Resolution",
      Connectivity: "Dual-Band 2.4GHz & 5GHz High-Speed WiFi",
      "Night Vision": "Specialized IR Array for Zero Window Glass Reflection",
      Storage: "MicroSD up to 128GB + Tuya Cloud Storage",
    },
    tags: ["Tuya", "Window Camera", "3MP", "Dual Band 5G", "Indoor Security"],
  },
  {
    id: "tysh-cm02",
    title: "Tuya TYSH-CM02 3MP 355-Degree Pan-Tilt Indoor Camera - WiFi",
    slug: "tysh-cm02-3mp-pan-tilt-indoor-camera",
    category: "Smart Security Cameras",
    price_pkr: 4200,
    stock: 80,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Classic White",
    image_url:
      "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&auto=format&fit=crop&q=80",
    description:
      "Motorized 355-degree horizontal pan and 90-degree vertical tilt with AI human tracking. Automatically follows moving people across the room with two-way voice talk.",
    specs: {
      Model: "TYSH-CM02",
      Resolution: "3MP HD Video",
      Rotation: "355° Pan / 90° Tilt Motorized Rotation",
      Tracking: "AI Smart Human Motion Tracking",
      Audio: "Two-Way Audio with Noise Cancellation",
    },
    tags: ["Tuya", "PTZ Camera", "3MP", "Indoor Camera", "Motion Tracking"],
  },
  {
    id: "tysh-cm10",
    title: "Tuya TYSH-CM10 4MP Outdoor Dual-Floodlight Camera - WiFi",
    slug: "tysh-cm10-4mp-outdoor-floodlight-security-camera",
    category: "Smart Security Cameras",
    price_pkr: 8540,
    stock: 45,
    discount_pct: 0,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Industrial White Housing",
    image_url:
      "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&auto=format&fit=crop&q=80",
    description:
      "4MP Ultra-HD security camera integrated with dual high-power 2000-lumen LED floodlight panels. Automatically illuminates driveways and yards upon detecting intruders with vivid full-color night vision.",
    specs: {
      Model: "TYSH-CM10",
      Resolution: "4MP Super HD (2560 x 1440)",
      Floodlights: "Dual LED Floodlights (2000 Lumens / 5000K Daylight)",
      "Night Vision": "Full Color Starlight Night Vision up to 25m",
      Weatherproof: "IP65 Waterproof Aluminum Housing",
      Alarm: "110dB Built-in Security Siren",
    },
    tags: ["Tuya", "Floodlight Camera", "4MP", "Full Color Night Vision", "Outdoor Camera"],
  },
  {
    id: "tysh-c316",
    title: "Tuya TYSH-C316 3MP Solar Powered Battery Camera - WiFi",
    slug: "tysh-c316-solar-battery-security-camera",
    category: "Smart Security Cameras",
    price_pkr: 11200,
    stock: 40,
    discount_pct: 5,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Weather-Resistant White",
    image_url:
      "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&auto=format&fit=crop&q=80",
    description:
      "Zero wiring required: equipped with high-capacity rechargeable batteries and an included monocrystalline solar charging panel that keeps the camera charged 365 days a year in sunlight.",
    specs: {
      Model: "TYSH-C316",
      "Solar Panel": "High-Efficiency 3.5W Monocrystalline Solar Panel Included",
      Battery: "9600mAh High-Capacity Rechargeable Lithium",
      Sensor: "Ultra-Low Power PIR Motion Wake-Up in <0.2 seconds",
      Resolution: "3MP (2048 x 1536) Resolution",
    },
    tags: ["Tuya", "Solar Camera", "Battery Camera", "Wire-Free", "Outdoor Security"],
  },
  {
    id: "tysh-ck13",
    title: "Tuya TYSH-CK13 4-Channel 3MP Wireless NVR System - WiFi/IP",
    slug: "tysh-ck13-4channel-wireless-nvr-security-kit",
    category: "Smart Security Cameras",
    price_pkr: 51800,
    stock: 15,
    discount_pct: 8,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Professional Black & White",
    image_url:
      "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&auto=format&fit=crop&q=80",
    description:
      "Complete commercial wireless video surveillance system: includes 4x 3MP IP66 outdoor bullet cameras and a dedicated 4CH Wireless NVR recorder. Cameras auto-pair right out of the box with up to 300m line-of-sight wireless range.",
    specs: {
      Model: "TYSH-CK13",
      "Kit Contents": "4x 3MP Wireless Cameras + 1x 4CH NVR Station + Power Supplies",
      Transmission: "Dedicated 5GHz Encrypted Camera Transmission Mesh (No WiFi lag)",
      Storage: "Supports up to 8TB SATA 3.5-inch Surveillance Hard Drive",
      "Remote View": "Tuya App iOS & Android + HDMI/VGA Monitor Output",
    },
    tags: ["Tuya", "NVR Kit", "Wireless CCTV", "4-Camera Kit", "Commercial Security"],
  },

  // ==========================================
  // SECTION 10: SMART VIDEO DOORBELLS (Pages 58–59)
  // ==========================================
  {
    id: "tysh-c516",
    title: "Tuya TYSH-C516 2MP 160-Degree Smart Video Doorbell - WiFi",
    slug: "tysh-c516-1080p-smart-video-doorbell-chime",
    category: "Smart Video Doorbells",
    price_pkr: 8400,
    stock: 50,
    discount_pct: 0,
    rating: 4.9,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Gloss Black Faceplate",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "1080P full HD smart video doorbell with 160-degree ultra-wide lens that sees visitors head-to-toe and ground packages. Includes wireless plug-in indoor chime with 58 selectable ringtones.",
    specs: {
      Model: "TYSH-C516",
      Resolution: "1080P Full HD with WDR Backlight Compensation",
      "Field of View": "160° Diagonal Ultra-Wide Angle",
      Chime: "Wireless Indoor Chime Unit Included (Plug-and-play)",
      Power: "Dual 18650 Rechargeable Batteries (5200mAh) or 12-24V AC hardwire",
    },
    tags: ["Tuya", "Video Doorbell", "1080P", "Wireless Chime", "Head to Toe View"],
  },
  {
    id: "tysh-c556",
    title: "Tuya TYSH-C556 2MP IP65 Waterproof Video Doorbell - WiFi",
    slug: "tysh-c556-ip65-waterproof-video-doorbell",
    category: "Smart Video Doorbells",
    price_pkr: 8400,
    stock: 45,
    discount_pct: 0,
    rating: 4.8,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Weatherproof Gunmetal Gray",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Certified IP65 waterproof housing engineered for uncovered gates and direct rain exposure. Instant video call to your smartphone whenever a visitor rings the bell.",
    specs: {
      Model: "TYSH-C556",
      Protection: "IP65 Weatherproof",
      Battery: "Built-in 5000mAh Lithium Rechargeable",
      "Night Vision": "6x 850nm High-Power Infrared LEDs",
    },
    tags: ["Tuya", "Video Doorbell", "IP65", "Gate Intercom", "Smart Doorbell"],
  },
  {
    id: "tysh-vd2a",
    title: "Tuya TYSH-VD2A 10.1-Inch 2-Wire Video Intercom Station - WiFi",
    slug: "tysh-vd2a-2wire-video-intercom-10inch-screen",
    category: "Smart Video Doorbells",
    price_pkr: 30520,
    stock: 25,
    discount_pct: 0,
    rating: 5.0,
    availability: "in_stock",
    manufacturer: "TYSH / Tuya Smart",
    color: "Brushed Aluminum & Glass",
    image_url:
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
    description:
      "Premium villa intercom system: connects via existing simple 2-wire non-polarity doorbell wiring. Includes an outdoor anti-vandal camera unit with RFID card reader and a luxury 10.1-inch color indoor touch screen console with remote gate release.",
    specs: {
      Model: "TYSH-VD2A",
      Wiring: "2-Wire Non-Polarity Connection (Up to 100 meters)",
      "Indoor Console": "10.1-inch Capacitive IPS Color Touch Screen",
      "Outdoor Station": "Aluminum Anti-Vandal IP65 Camera + RFID Card Unlock",
      "Gate Control": "Directly triggers electronic gate strikes or barrier arms",
    },
    tags: ["Tuya", "Villa Intercom", "10.1-inch Touch Screen", "2-Wire Intercom", "Gate Release"],
  },
];
